// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukunqcgngsfewnmtiiiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrdW5xY2duZ3NmZXdubXRpaWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjgxNDMsImV4cCI6MjA2NDgwNDE0M30.YmlpYHetxpFrPfEafZV2RkR3EcbAcUraFbAA5Vdw2ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);